routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [DashboardController::class, 'home'])->name('home');

Route::get('/dashboard', [DashboardController::class, 'dashboard'])->middleware(['auth'])->name('dashboard');

Route::get('/account', [DashboardController::class, 'home'])->name('account');

Route::resource('posts', PostController::class);

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/about.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

resources/views/dashboard.blade.php
<x-app-layout>
  <x-slot name="slot">
    <div class="row gx-4 gx-lg-5 justify-content-center py-6">
      <div class="col-md-10 col-lg-8 col-xl-10">
        @forelse($posts as $post)
          <div class="md:mb-5 p-3">
              <a href="/posts/{{ $post->id }}" class="block rounded-lg relative p-5 transform transition-all duration-300 scale-100 hover:scale-95" style="background: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url({{ asset($post->image) }}) center; background-size: cover;">
                  <div class="h-48"></div>
                  <h2 class="text-white text-2xl font-bold leading-tight mb-3 pr-5">{{ $post->title }}</h2>
                  <div class="flex w-full items-center text-sm text-gray-300 font-medium">
                      <div class="flex-1 flex items-center">
                          <div class="rounded-full w-8 h-8 mr-3" style="background: url(https://randomuser.me/api/portraits/women/74.jpg) center; background-size: cover;"></div>
                          <div>{{ $post->author() }}</div>
                      </div>
                      <div><i class="mdi mdi-clock"></i> {{ $post->created_at->diffForHumans() }}</div>
                  </div>
              </a>
          </div>
        @empty
          <p>You have not written any posts yet. <a class="text-primary" href="{{ route('posts.create') }}">Start writing now</a></p>
        @endforelse
        <!-- Pager-->
        {{ $posts->links('vendor.pagination.simple-bootstrap-4') }}
      </div>
    </div>
  </x-slot>
</x-app-layout>

resources/views/index.blade.php
<x-app-layout>
  <x-slot name="slot">
    <header class="masthead" style="background-image: url('assets/img/contact-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="page-heading">
                        <h1>Medium</h1>
                        <span class="subheading">Feel. Write. Share.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="row gx-4 gx-lg-5 justify-content-center py-6">
      <!--<div class="col-md-10 col-lg-8 col-xl-10">
        @forelse($posts as $post)
          <div class="md:mb-5 p-3">
              <a href="/posts/{{ $post->id }}" class="block rounded-lg relative p-5 transform transition-all duration-300 scale-100 hover:scale-95" style="background: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url({{ asset($post->image) }}) center; background-size: cover;">
                  <div class="h-48"></div>
                  <h2 class="text-white text-2xl font-bold leading-tight mb-3 pr-5">{{ $post->title }}</h2>
                  <div class="flex w-full items-center text-sm text-gray-300 font-medium">
                      <div class="flex-1 flex items-center">
                          <div class="rounded-full w-8 h-8 mr-3" style="background: url(https://randomuser.me/api/portraits/women/74.jpg) center; background-size: cover;"></div>
                          <div>{{ $post->author() }}</div>
                      </div>
                      <div><i class="mdi mdi-thumb-up"></i> {{ $post->created_at->diffForHumans() }}</div>
                  </div>
              </a>
          </div>
        @empty
          <p>You have not written any posts yet. <a class="text-primary" href="{{ route('posts.create') }}">Start writing now</a></p>
        @endforelse
    -->
            <div class="col-md-10 col-lg-8 col-xl-8">
                @forelse($posts as $post)
                <div class="post-preview">
                    <a href="posts/{{ $post->id }}">
                        <h2 class="post-title">{{ $post->title }}</h2>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">{{ $post->author() }}</a>
                        {{ $post->created_at->diffForHumans() }}
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
                <!-- Pager-->
                @empty
                  <p>You have not written any posts yet. <a class="text-primary" href="{{ route('posts.create') }}">Start writing now</a></p>
                @endforelse
                {{ $posts->links('vendor.pagination.simple-bootstrap-4') }}
            </div>
        </div>
    </div>
  </x-slot>
</x-app-layout>

<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>

resources/views/post.blade.php
<x-app-layout>
  <x-slot name="slot">
    <div class="w-full bg-cover bg-center" style="height:32rem; background-image: url({{ asset($post->image) }});">
        <div class="flex items-center justify-center h-full w-full bg-gray-900 bg-opacity-50">
            <div class="text-center">
                <h1 class="text-white text-4xl font-semibold uppercase md:text-4xl">{{ $post->title }}</h1>
                <p class="text-white text-xl pt-3">Posted by {{ $post->author() }} {{ $post->created_at->diffForHumans() }}</p>
            </div>
        </div>
    </div>
    <!-- Post Content-->
    <article class="md:p-12 p-4" id="content">
        <div class="flex flex-col max-w-full md:flex-row my-10">
            <div class="md:flex md:w-2/3 md:pr-6 md:pl-6">
                <div style="white-space: pre-wrap;">{!! $post->content !!}</div>
            </div>
            <div class="flex flex-col pb-6 md:py-0 md:w-1/3 md:pl-6 pt-6">
                <h1 class="text-gray-900 text-2xl font-semibold">Tags</h1>
                <p>{{ $post->tags }}</p>

                <h1 class="text-gray-900 text-2xl font-semibold mt-6">Categories</h1>
                <ul>
                    @foreach($categories as $cat)
                    <li>{{ $cat }}</li>
                    @endforeach
                </ul>

                <h1 class="text-gray-900 text-2xl font-semibold mt-6">Claps</h1>
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" />
                    </svg>
                </p>
                <p>{{ $post->claps }} claps</p>
            </div>
        </div>
    </article>
  </x-slot>
</x-app-layout>

resources/views/write-post.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      Write Post
    </h2>
  </x-slot>

  <x-slot name="slot">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 ">
        <div class="col-md-10 col-lg-8 col-xl-7">
          @if (session('status'))
              <div class="alert alert-success p-4">
                  {{ session('status') }}
              </div>
          @endif
          @if ($errors->any())
            <div class="alert alert-danger p-4">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li class="text-red-500">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
          @endif
          <form action="{{ route('posts.store') }}" method="post" enctype="multipart/form-data" onsubmit="document.getElementById('content').value = document.getElementById('wysiwyg').contentDocument.body.innerHTML; return document.activeElement.getAttribute('value') == 'Submit'">
            @csrf
            <div class="form-floating p-4">
              <label for="name">Title</label><br>
              <input class="form-control w-full" id="title" name="title" type="text" required="required" value="{{ old('title') }}" />
            </div>
            <div class="form-floating p-4">
              <label for="name">Banner Image</label><br>
              <input class="form-control w-full" id="image" name="image" type="file" required="required" value="{{ old('image') }}" />
            </div>
            <div class="form-floating p-4">
              <label for="name">Category</label><br>
              <!-- notice how i put [] after category to make it an array for multiple select -->
              <select class="form-control w-full" name="category[]" required="required" value="{{ old('category[]') }}" multiple="true">
                @foreach($categories as $cat)
                <option value="{{ $cat->id }}">{{ $cat->title }}</option>
                @endforeach
              </select><br>
              <small>select as many as apply</small>
            </div>
            <!--<div class="form-floating p-4">
              <label for="name">Content</label><br>
              <textarea class="form-control w-full" id="content" name="content" required="required">{{ old('content') }}</textarea>
            </div>-->
            <input type="hidden" name="content" id="content">
            <div class="form-floating p-4">
              <label for="name">Tags</label><br>
              <textarea class="form-control w-full" id="tags" name="tags" required="required">{{ old('tags') }}</textarea><br>
              <small>separate by commas</small>
            </div>

            <div class="w-full rounded-xl bg-white p-5 text-black" x-data="app()" x-init="init($refs.wysiwyg, `{{ old('content') }}`)">
                <label>Content</label>
                <div class="border border-gray-400 overflow-hidden">
                    <div class="w-full flex border-b border-gray-200 text-xl text-gray-600">
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('bold')">
                            <i class="mdi mdi-format-bold"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('italic')">
                            <i class="mdi mdi-format-italic"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 mr-1 hover:text-indigo-500 active:bg-gray-50" @click="format('underline')">
                            <i class="mdi mdi-format-underline"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-l border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('formatBlock','P')">
                            <i class="mdi mdi-format-paragraph"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('formatBlock','H1')">
                            <i class="mdi mdi-format-header-1"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('formatBlock','H2')">
                            <i class="mdi mdi-format-header-2"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 mr-1 hover:text-indigo-500 active:bg-gray-50" @click="format('formatBlock','H3')">
                            <i class="mdi mdi-format-header-3"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-l border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('insertUnorderedList')">
                            <i class="mdi mdi-format-list-bulleted"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 mr-1 hover:text-indigo-500 active:bg-gray-50" @click="format('insertOrderedList')">
                            <i class="mdi mdi-format-list-numbered"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-l border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('justifyLeft')">
                            <i class="mdi mdi-format-align-left"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('justifyCenter')">
                            <i class="mdi mdi-format-align-center"></i>
                        </button>
                        <button class="outline-none focus:outline-none border-r border-gray-200 w-10 h-10 hover:text-indigo-500 active:bg-gray-50" @click="format('justifyRight')">
                            <i class="mdi mdi-format-align-right"></i>
                        </button>
                    </div>
                    <div class="w-full">
                        <iframe x-ref="wysiwyg" class="w-full h-96 overflow-y-auto" id="wysiwyg"></iframe>
                    </div>
                </div>
            </div>
            <div class="form-floating p-4 mb-12">
              <input class="btn btn-primary text-uppercase form-control w-full p-2 bg-black text-white" type="submit" value="Submit">
            </div>
          </form>
        </div>
      </div>
    </div>
  </x-slot>
</x-app-layout>